// Code generated by 'yaegi extract github.com/slok/sloth/pkg/common/model'. DO NOT EDIT.

package custom

import (
	"github.com/slok/sloth/pkg/common/model"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/slok/sloth/pkg/common/model/model"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ModeCLIGenKubernetes":        reflect.ValueOf(constant.MakeFromLiteral("\"cli-gen-k8s\"", token.STRING, 0)),
		"ModeCLIGenOpenSLO":           reflect.ValueOf(constant.MakeFromLiteral("\"cli-gen-openslo\"", token.STRING, 0)),
		"ModeCLIGenPrometheus":        reflect.ValueOf(constant.MakeFromLiteral("\"cli-gen-prom\"", token.STRING, 0)),
		"ModeControllerGenKubernetes": reflect.ValueOf(constant.MakeFromLiteral("\"ctrl-gen-k8s\"", token.STRING, 0)),
		"ModeTest":                    reflect.ValueOf(constant.MakeFromLiteral("\"test\"", token.STRING, 0)),
		"PageAlertSeverity":           reflect.ValueOf(model.PageAlertSeverity),
		"PromQueryTPLKeyWindow":       reflect.ValueOf(constant.MakeFromLiteral("\"window\"", token.STRING, 0)),
		"TicketAlertSeverity":         reflect.ValueOf(model.TicketAlertSeverity),
		"UnknownAlertSeverity":        reflect.ValueOf(model.UnknownAlertSeverity),

		// type definitions
		"AlertSeverity":      reflect.ValueOf((*model.AlertSeverity)(nil)),
		"Info":               reflect.ValueOf((*model.Info)(nil)),
		"MWMBAlert":          reflect.ValueOf((*model.MWMBAlert)(nil)),
		"MWMBAlertGroup":     reflect.ValueOf((*model.MWMBAlertGroup)(nil)),
		"Mode":               reflect.ValueOf((*model.Mode)(nil)),
		"PromAlertMeta":      reflect.ValueOf((*model.PromAlertMeta)(nil)),
		"PromRuleGroup":      reflect.ValueOf((*model.PromRuleGroup)(nil)),
		"PromSLI":            reflect.ValueOf((*model.PromSLI)(nil)),
		"PromSLIEvents":      reflect.ValueOf((*model.PromSLIEvents)(nil)),
		"PromSLIRaw":         reflect.ValueOf((*model.PromSLIRaw)(nil)),
		"PromSLO":            reflect.ValueOf((*model.PromSLO)(nil)),
		"PromSLOGroup":       reflect.ValueOf((*model.PromSLOGroup)(nil)),
		"PromSLOGroupSource": reflect.ValueOf((*model.PromSLOGroupSource)(nil)),
		"PromSLORules":       reflect.ValueOf((*model.PromSLORules)(nil)),
	}
}
