// Code generated by 'yaegi extract github.com/prometheus/prometheus/model/rulefmt'. DO NOT EDIT.

package custom

import (
	"github.com/prometheus/prometheus/model/rulefmt"
	"reflect"
)

func init() {
	Symbols["github.com/prometheus/prometheus/model/rulefmt/rulefmt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Parse":     reflect.ValueOf(rulefmt.Parse),
		"ParseFile": reflect.ValueOf(rulefmt.ParseFile),

		// type definitions
		"Error":         reflect.ValueOf((*rulefmt.Error)(nil)),
		"Rule":          reflect.ValueOf((*rulefmt.Rule)(nil)),
		"RuleGroup":     reflect.ValueOf((*rulefmt.RuleGroup)(nil)),
		"RuleGroupNode": reflect.ValueOf((*rulefmt.RuleGroupNode)(nil)),
		"RuleGroups":    reflect.ValueOf((*rulefmt.RuleGroups)(nil)),
		"RuleNode":      reflect.ValueOf((*rulefmt.RuleNode)(nil)),
		"WrappedError":  reflect.ValueOf((*rulefmt.WrappedError)(nil)),
	}
}
