// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storagemock

import (
	"context"
	"time"

	"github.com/slok/sloth/internal/http/backend/model"
	"github.com/slok/sloth/internal/http/backend/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceGetter creates a new instance of ServiceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceGetter {
	mock := &ServiceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceGetter is an autogenerated mock type for the ServiceGetter type
type ServiceGetter struct {
	mock.Mock
}

type ServiceGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceGetter) EXPECT() *ServiceGetter_Expecter {
	return &ServiceGetter_Expecter{mock: &_m.Mock}
}

// ListAllServiceAndAlerts provides a mock function for the type ServiceGetter
func (_mock *ServiceGetter) ListAllServiceAndAlerts(ctx context.Context) ([]storage.ServiceAndAlerts, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllServiceAndAlerts")
	}

	var r0 []storage.ServiceAndAlerts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]storage.ServiceAndAlerts, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []storage.ServiceAndAlerts); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.ServiceAndAlerts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceGetter_ListAllServiceAndAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllServiceAndAlerts'
type ServiceGetter_ListAllServiceAndAlerts_Call struct {
	*mock.Call
}

// ListAllServiceAndAlerts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ServiceGetter_Expecter) ListAllServiceAndAlerts(ctx interface{}) *ServiceGetter_ListAllServiceAndAlerts_Call {
	return &ServiceGetter_ListAllServiceAndAlerts_Call{Call: _e.mock.On("ListAllServiceAndAlerts", ctx)}
}

func (_c *ServiceGetter_ListAllServiceAndAlerts_Call) Run(run func(ctx context.Context)) *ServiceGetter_ListAllServiceAndAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ServiceGetter_ListAllServiceAndAlerts_Call) Return(serviceAndAlertss []storage.ServiceAndAlerts, err error) *ServiceGetter_ListAllServiceAndAlerts_Call {
	_c.Call.Return(serviceAndAlertss, err)
	return _c
}

func (_c *ServiceGetter_ListAllServiceAndAlerts_Call) RunAndReturn(run func(ctx context.Context) ([]storage.ServiceAndAlerts, error)) *ServiceGetter_ListAllServiceAndAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// ListServiceAndAlertsByServiceSearch provides a mock function for the type ServiceGetter
func (_mock *ServiceGetter) ListServiceAndAlertsByServiceSearch(ctx context.Context, serviceSearchInput string) ([]storage.ServiceAndAlerts, error) {
	ret := _mock.Called(ctx, serviceSearchInput)

	if len(ret) == 0 {
		panic("no return value specified for ListServiceAndAlertsByServiceSearch")
	}

	var r0 []storage.ServiceAndAlerts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]storage.ServiceAndAlerts, error)); ok {
		return returnFunc(ctx, serviceSearchInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []storage.ServiceAndAlerts); ok {
		r0 = returnFunc(ctx, serviceSearchInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.ServiceAndAlerts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, serviceSearchInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceGetter_ListServiceAndAlertsByServiceSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServiceAndAlertsByServiceSearch'
type ServiceGetter_ListServiceAndAlertsByServiceSearch_Call struct {
	*mock.Call
}

// ListServiceAndAlertsByServiceSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceSearchInput string
func (_e *ServiceGetter_Expecter) ListServiceAndAlertsByServiceSearch(ctx interface{}, serviceSearchInput interface{}) *ServiceGetter_ListServiceAndAlertsByServiceSearch_Call {
	return &ServiceGetter_ListServiceAndAlertsByServiceSearch_Call{Call: _e.mock.On("ListServiceAndAlertsByServiceSearch", ctx, serviceSearchInput)}
}

func (_c *ServiceGetter_ListServiceAndAlertsByServiceSearch_Call) Run(run func(ctx context.Context, serviceSearchInput string)) *ServiceGetter_ListServiceAndAlertsByServiceSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceGetter_ListServiceAndAlertsByServiceSearch_Call) Return(serviceAndAlertss []storage.ServiceAndAlerts, err error) *ServiceGetter_ListServiceAndAlertsByServiceSearch_Call {
	_c.Call.Return(serviceAndAlertss, err)
	return _c
}

func (_c *ServiceGetter_ListServiceAndAlertsByServiceSearch_Call) RunAndReturn(run func(ctx context.Context, serviceSearchInput string) ([]storage.ServiceAndAlerts, error)) *ServiceGetter_ListServiceAndAlertsByServiceSearch_Call {
	_c.Call.Return(run)
	return _c
}

// NewSLOGetter creates a new instance of SLOGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLOGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLOGetter {
	mock := &SLOGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SLOGetter is an autogenerated mock type for the SLOGetter type
type SLOGetter struct {
	mock.Mock
}

type SLOGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *SLOGetter) EXPECT() *SLOGetter_Expecter {
	return &SLOGetter_Expecter{mock: &_m.Mock}
}

// GetSLIAvailabilityInRange provides a mock function for the type SLOGetter
func (_mock *SLOGetter) GetSLIAvailabilityInRange(ctx context.Context, sloID string, from time.Time, to time.Time, step time.Duration) ([]model.DataPoint, error) {
	ret := _mock.Called(ctx, sloID, from, to, step)

	if len(ret) == 0 {
		panic("no return value specified for GetSLIAvailabilityInRange")
	}

	var r0 []model.DataPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, time.Duration) ([]model.DataPoint, error)); ok {
		return returnFunc(ctx, sloID, from, to, step)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, time.Duration) []model.DataPoint); ok {
		r0 = returnFunc(ctx, sloID, from, to, step)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DataPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, time.Duration) error); ok {
		r1 = returnFunc(ctx, sloID, from, to, step)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_GetSLIAvailabilityInRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSLIAvailabilityInRange'
type SLOGetter_GetSLIAvailabilityInRange_Call struct {
	*mock.Call
}

// GetSLIAvailabilityInRange is a helper method to define mock.On call
//   - ctx context.Context
//   - sloID string
//   - from time.Time
//   - to time.Time
//   - step time.Duration
func (_e *SLOGetter_Expecter) GetSLIAvailabilityInRange(ctx interface{}, sloID interface{}, from interface{}, to interface{}, step interface{}) *SLOGetter_GetSLIAvailabilityInRange_Call {
	return &SLOGetter_GetSLIAvailabilityInRange_Call{Call: _e.mock.On("GetSLIAvailabilityInRange", ctx, sloID, from, to, step)}
}

func (_c *SLOGetter_GetSLIAvailabilityInRange_Call) Run(run func(ctx context.Context, sloID string, from time.Time, to time.Time, step time.Duration)) *SLOGetter_GetSLIAvailabilityInRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *SLOGetter_GetSLIAvailabilityInRange_Call) Return(dataPoints []model.DataPoint, err error) *SLOGetter_GetSLIAvailabilityInRange_Call {
	_c.Call.Return(dataPoints, err)
	return _c
}

func (_c *SLOGetter_GetSLIAvailabilityInRange_Call) RunAndReturn(run func(ctx context.Context, sloID string, from time.Time, to time.Time, step time.Duration) ([]model.DataPoint, error)) *SLOGetter_GetSLIAvailabilityInRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetSLIAvailabilityInRangeAutoStep provides a mock function for the type SLOGetter
func (_mock *SLOGetter) GetSLIAvailabilityInRangeAutoStep(ctx context.Context, sloID string, from time.Time, to time.Time) ([]model.DataPoint, error) {
	ret := _mock.Called(ctx, sloID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetSLIAvailabilityInRangeAutoStep")
	}

	var r0 []model.DataPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]model.DataPoint, error)); ok {
		return returnFunc(ctx, sloID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []model.DataPoint); ok {
		r0 = returnFunc(ctx, sloID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DataPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, sloID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSLIAvailabilityInRangeAutoStep'
type SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call struct {
	*mock.Call
}

// GetSLIAvailabilityInRangeAutoStep is a helper method to define mock.On call
//   - ctx context.Context
//   - sloID string
//   - from time.Time
//   - to time.Time
func (_e *SLOGetter_Expecter) GetSLIAvailabilityInRangeAutoStep(ctx interface{}, sloID interface{}, from interface{}, to interface{}) *SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call {
	return &SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call{Call: _e.mock.On("GetSLIAvailabilityInRangeAutoStep", ctx, sloID, from, to)}
}

func (_c *SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call) Run(run func(ctx context.Context, sloID string, from time.Time, to time.Time)) *SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call) Return(dataPoints []model.DataPoint, err error) *SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call {
	_c.Call.Return(dataPoints, err)
	return _c
}

func (_c *SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call) RunAndReturn(run func(ctx context.Context, sloID string, from time.Time, to time.Time) ([]model.DataPoint, error)) *SLOGetter_GetSLIAvailabilityInRangeAutoStep_Call {
	_c.Call.Return(run)
	return _c
}

// GetSLOInstantDetails provides a mock function for the type SLOGetter
func (_mock *SLOGetter) GetSLOInstantDetails(ctx context.Context, sloID string) (*storage.SLOInstantDetails, error) {
	ret := _mock.Called(ctx, sloID)

	if len(ret) == 0 {
		panic("no return value specified for GetSLOInstantDetails")
	}

	var r0 *storage.SLOInstantDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*storage.SLOInstantDetails, error)); ok {
		return returnFunc(ctx, sloID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *storage.SLOInstantDetails); ok {
		r0 = returnFunc(ctx, sloID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.SLOInstantDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sloID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_GetSLOInstantDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSLOInstantDetails'
type SLOGetter_GetSLOInstantDetails_Call struct {
	*mock.Call
}

// GetSLOInstantDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - sloID string
func (_e *SLOGetter_Expecter) GetSLOInstantDetails(ctx interface{}, sloID interface{}) *SLOGetter_GetSLOInstantDetails_Call {
	return &SLOGetter_GetSLOInstantDetails_Call{Call: _e.mock.On("GetSLOInstantDetails", ctx, sloID)}
}

func (_c *SLOGetter_GetSLOInstantDetails_Call) Run(run func(ctx context.Context, sloID string)) *SLOGetter_GetSLOInstantDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLOGetter_GetSLOInstantDetails_Call) Return(sLOInstantDetails *storage.SLOInstantDetails, err error) *SLOGetter_GetSLOInstantDetails_Call {
	_c.Call.Return(sLOInstantDetails, err)
	return _c
}

func (_c *SLOGetter_GetSLOInstantDetails_Call) RunAndReturn(run func(ctx context.Context, sloID string) (*storage.SLOInstantDetails, error)) *SLOGetter_GetSLOInstantDetails_Call {
	_c.Call.Return(run)
	return _c
}

// ListSLOInstantDetails provides a mock function for the type SLOGetter
func (_mock *SLOGetter) ListSLOInstantDetails(ctx context.Context) ([]storage.SLOInstantDetails, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSLOInstantDetails")
	}

	var r0 []storage.SLOInstantDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]storage.SLOInstantDetails, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []storage.SLOInstantDetails); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.SLOInstantDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_ListSLOInstantDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLOInstantDetails'
type SLOGetter_ListSLOInstantDetails_Call struct {
	*mock.Call
}

// ListSLOInstantDetails is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SLOGetter_Expecter) ListSLOInstantDetails(ctx interface{}) *SLOGetter_ListSLOInstantDetails_Call {
	return &SLOGetter_ListSLOInstantDetails_Call{Call: _e.mock.On("ListSLOInstantDetails", ctx)}
}

func (_c *SLOGetter_ListSLOInstantDetails_Call) Run(run func(ctx context.Context)) *SLOGetter_ListSLOInstantDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetails_Call) Return(sLOInstantDetailss []storage.SLOInstantDetails, err error) *SLOGetter_ListSLOInstantDetails_Call {
	_c.Call.Return(sLOInstantDetailss, err)
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetails_Call) RunAndReturn(run func(ctx context.Context) ([]storage.SLOInstantDetails, error)) *SLOGetter_ListSLOInstantDetails_Call {
	_c.Call.Return(run)
	return _c
}

// ListSLOInstantDetailsBySLOSearch provides a mock function for the type SLOGetter
func (_mock *SLOGetter) ListSLOInstantDetailsBySLOSearch(ctx context.Context, sloSearchInput string) ([]storage.SLOInstantDetails, error) {
	ret := _mock.Called(ctx, sloSearchInput)

	if len(ret) == 0 {
		panic("no return value specified for ListSLOInstantDetailsBySLOSearch")
	}

	var r0 []storage.SLOInstantDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]storage.SLOInstantDetails, error)); ok {
		return returnFunc(ctx, sloSearchInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []storage.SLOInstantDetails); ok {
		r0 = returnFunc(ctx, sloSearchInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.SLOInstantDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sloSearchInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_ListSLOInstantDetailsBySLOSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLOInstantDetailsBySLOSearch'
type SLOGetter_ListSLOInstantDetailsBySLOSearch_Call struct {
	*mock.Call
}

// ListSLOInstantDetailsBySLOSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - sloSearchInput string
func (_e *SLOGetter_Expecter) ListSLOInstantDetailsBySLOSearch(ctx interface{}, sloSearchInput interface{}) *SLOGetter_ListSLOInstantDetailsBySLOSearch_Call {
	return &SLOGetter_ListSLOInstantDetailsBySLOSearch_Call{Call: _e.mock.On("ListSLOInstantDetailsBySLOSearch", ctx, sloSearchInput)}
}

func (_c *SLOGetter_ListSLOInstantDetailsBySLOSearch_Call) Run(run func(ctx context.Context, sloSearchInput string)) *SLOGetter_ListSLOInstantDetailsBySLOSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetailsBySLOSearch_Call) Return(sLOInstantDetailss []storage.SLOInstantDetails, err error) *SLOGetter_ListSLOInstantDetailsBySLOSearch_Call {
	_c.Call.Return(sLOInstantDetailss, err)
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetailsBySLOSearch_Call) RunAndReturn(run func(ctx context.Context, sloSearchInput string) ([]storage.SLOInstantDetails, error)) *SLOGetter_ListSLOInstantDetailsBySLOSearch_Call {
	_c.Call.Return(run)
	return _c
}

// ListSLOInstantDetailsService provides a mock function for the type SLOGetter
func (_mock *SLOGetter) ListSLOInstantDetailsService(ctx context.Context, serviceID string) ([]storage.SLOInstantDetails, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for ListSLOInstantDetailsService")
	}

	var r0 []storage.SLOInstantDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]storage.SLOInstantDetails, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []storage.SLOInstantDetails); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.SLOInstantDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_ListSLOInstantDetailsService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLOInstantDetailsService'
type SLOGetter_ListSLOInstantDetailsService_Call struct {
	*mock.Call
}

// ListSLOInstantDetailsService is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID string
func (_e *SLOGetter_Expecter) ListSLOInstantDetailsService(ctx interface{}, serviceID interface{}) *SLOGetter_ListSLOInstantDetailsService_Call {
	return &SLOGetter_ListSLOInstantDetailsService_Call{Call: _e.mock.On("ListSLOInstantDetailsService", ctx, serviceID)}
}

func (_c *SLOGetter_ListSLOInstantDetailsService_Call) Run(run func(ctx context.Context, serviceID string)) *SLOGetter_ListSLOInstantDetailsService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetailsService_Call) Return(sLOInstantDetailss []storage.SLOInstantDetails, err error) *SLOGetter_ListSLOInstantDetailsService_Call {
	_c.Call.Return(sLOInstantDetailss, err)
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetailsService_Call) RunAndReturn(run func(ctx context.Context, serviceID string) ([]storage.SLOInstantDetails, error)) *SLOGetter_ListSLOInstantDetailsService_Call {
	_c.Call.Return(run)
	return _c
}

// ListSLOInstantDetailsServiceBySLOSearch provides a mock function for the type SLOGetter
func (_mock *SLOGetter) ListSLOInstantDetailsServiceBySLOSearch(ctx context.Context, serviceID string, sloSearchInput string) ([]storage.SLOInstantDetails, error) {
	ret := _mock.Called(ctx, serviceID, sloSearchInput)

	if len(ret) == 0 {
		panic("no return value specified for ListSLOInstantDetailsServiceBySLOSearch")
	}

	var r0 []storage.SLOInstantDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]storage.SLOInstantDetails, error)); ok {
		return returnFunc(ctx, serviceID, sloSearchInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []storage.SLOInstantDetails); ok {
		r0 = returnFunc(ctx, serviceID, sloSearchInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.SLOInstantDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, serviceID, sloSearchInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLOInstantDetailsServiceBySLOSearch'
type SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call struct {
	*mock.Call
}

// ListSLOInstantDetailsServiceBySLOSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID string
//   - sloSearchInput string
func (_e *SLOGetter_Expecter) ListSLOInstantDetailsServiceBySLOSearch(ctx interface{}, serviceID interface{}, sloSearchInput interface{}) *SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call {
	return &SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call{Call: _e.mock.On("ListSLOInstantDetailsServiceBySLOSearch", ctx, serviceID, sloSearchInput)}
}

func (_c *SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call) Run(run func(ctx context.Context, serviceID string, sloSearchInput string)) *SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call) Return(sLOInstantDetailss []storage.SLOInstantDetails, err error) *SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call {
	_c.Call.Return(sLOInstantDetailss, err)
	return _c
}

func (_c *SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call) RunAndReturn(run func(ctx context.Context, serviceID string, sloSearchInput string) ([]storage.SLOInstantDetails, error)) *SLOGetter_ListSLOInstantDetailsServiceBySLOSearch_Call {
	_c.Call.Return(run)
	return _c
}
