// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package prometheusmock

import (
	"context"
	"time"

	"github.com/prometheus/client_golang/api/prometheus/v1"
	"github.com/prometheus/common/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPrometheusAPIClient creates a new instance of PrometheusAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrometheusAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrometheusAPIClient {
	mock := &PrometheusAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrometheusAPIClient is an autogenerated mock type for the PrometheusAPIClient type
type PrometheusAPIClient struct {
	mock.Mock
}

type PrometheusAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PrometheusAPIClient) EXPECT() *PrometheusAPIClient_Expecter {
	return &PrometheusAPIClient_Expecter{mock: &_m.Mock}
}

// AlertManagers provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) AlertManagers(ctx context.Context) (v1.AlertManagersResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AlertManagers")
	}

	var r0 v1.AlertManagersResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.AlertManagersResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.AlertManagersResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.AlertManagersResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_AlertManagers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlertManagers'
type PrometheusAPIClient_AlertManagers_Call struct {
	*mock.Call
}

// AlertManagers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) AlertManagers(ctx interface{}) *PrometheusAPIClient_AlertManagers_Call {
	return &PrometheusAPIClient_AlertManagers_Call{Call: _e.mock.On("AlertManagers", ctx)}
}

func (_c *PrometheusAPIClient_AlertManagers_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_AlertManagers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_AlertManagers_Call) Return(alertManagersResult v1.AlertManagersResult, err error) *PrometheusAPIClient_AlertManagers_Call {
	_c.Call.Return(alertManagersResult, err)
	return _c
}

func (_c *PrometheusAPIClient_AlertManagers_Call) RunAndReturn(run func(ctx context.Context) (v1.AlertManagersResult, error)) *PrometheusAPIClient_AlertManagers_Call {
	_c.Call.Return(run)
	return _c
}

// Alerts provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Alerts(ctx context.Context) (v1.AlertsResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Alerts")
	}

	var r0 v1.AlertsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.AlertsResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.AlertsResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.AlertsResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Alerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alerts'
type PrometheusAPIClient_Alerts_Call struct {
	*mock.Call
}

// Alerts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) Alerts(ctx interface{}) *PrometheusAPIClient_Alerts_Call {
	return &PrometheusAPIClient_Alerts_Call{Call: _e.mock.On("Alerts", ctx)}
}

func (_c *PrometheusAPIClient_Alerts_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_Alerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Alerts_Call) Return(alertsResult v1.AlertsResult, err error) *PrometheusAPIClient_Alerts_Call {
	_c.Call.Return(alertsResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Alerts_Call) RunAndReturn(run func(ctx context.Context) (v1.AlertsResult, error)) *PrometheusAPIClient_Alerts_Call {
	_c.Call.Return(run)
	return _c
}

// Buildinfo provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Buildinfo(ctx context.Context) (v1.BuildinfoResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Buildinfo")
	}

	var r0 v1.BuildinfoResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.BuildinfoResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.BuildinfoResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.BuildinfoResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Buildinfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Buildinfo'
type PrometheusAPIClient_Buildinfo_Call struct {
	*mock.Call
}

// Buildinfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) Buildinfo(ctx interface{}) *PrometheusAPIClient_Buildinfo_Call {
	return &PrometheusAPIClient_Buildinfo_Call{Call: _e.mock.On("Buildinfo", ctx)}
}

func (_c *PrometheusAPIClient_Buildinfo_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_Buildinfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Buildinfo_Call) Return(buildinfoResult v1.BuildinfoResult, err error) *PrometheusAPIClient_Buildinfo_Call {
	_c.Call.Return(buildinfoResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Buildinfo_Call) RunAndReturn(run func(ctx context.Context) (v1.BuildinfoResult, error)) *PrometheusAPIClient_Buildinfo_Call {
	_c.Call.Return(run)
	return _c
}

// CleanTombstones provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) CleanTombstones(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanTombstones")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrometheusAPIClient_CleanTombstones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanTombstones'
type PrometheusAPIClient_CleanTombstones_Call struct {
	*mock.Call
}

// CleanTombstones is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) CleanTombstones(ctx interface{}) *PrometheusAPIClient_CleanTombstones_Call {
	return &PrometheusAPIClient_CleanTombstones_Call{Call: _e.mock.On("CleanTombstones", ctx)}
}

func (_c *PrometheusAPIClient_CleanTombstones_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_CleanTombstones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_CleanTombstones_Call) Return(err error) *PrometheusAPIClient_CleanTombstones_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrometheusAPIClient_CleanTombstones_Call) RunAndReturn(run func(ctx context.Context) error) *PrometheusAPIClient_CleanTombstones_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Config(ctx context.Context) (v1.ConfigResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 v1.ConfigResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.ConfigResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.ConfigResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.ConfigResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type PrometheusAPIClient_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) Config(ctx interface{}) *PrometheusAPIClient_Config_Call {
	return &PrometheusAPIClient_Config_Call{Call: _e.mock.On("Config", ctx)}
}

func (_c *PrometheusAPIClient_Config_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Config_Call) Return(configResult v1.ConfigResult, err error) *PrometheusAPIClient_Config_Call {
	_c.Call.Return(configResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Config_Call) RunAndReturn(run func(ctx context.Context) (v1.ConfigResult, error)) *PrometheusAPIClient_Config_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSeries provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) DeleteSeries(ctx context.Context, matches []string, startTime time.Time, endTime time.Time) error {
	ret := _mock.Called(ctx, matches, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSeries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) error); ok {
		r0 = returnFunc(ctx, matches, startTime, endTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PrometheusAPIClient_DeleteSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSeries'
type PrometheusAPIClient_DeleteSeries_Call struct {
	*mock.Call
}

// DeleteSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
func (_e *PrometheusAPIClient_Expecter) DeleteSeries(ctx interface{}, matches interface{}, startTime interface{}, endTime interface{}) *PrometheusAPIClient_DeleteSeries_Call {
	return &PrometheusAPIClient_DeleteSeries_Call{Call: _e.mock.On("DeleteSeries", ctx, matches, startTime, endTime)}
}

func (_c *PrometheusAPIClient_DeleteSeries_Call) Run(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time)) *PrometheusAPIClient_DeleteSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_DeleteSeries_Call) Return(err error) *PrometheusAPIClient_DeleteSeries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PrometheusAPIClient_DeleteSeries_Call) RunAndReturn(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time) error) *PrometheusAPIClient_DeleteSeries_Call {
	_c.Call.Return(run)
	return _c
}

// Flags provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Flags(ctx context.Context) (v1.FlagsResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Flags")
	}

	var r0 v1.FlagsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.FlagsResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.FlagsResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.FlagsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Flags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flags'
type PrometheusAPIClient_Flags_Call struct {
	*mock.Call
}

// Flags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) Flags(ctx interface{}) *PrometheusAPIClient_Flags_Call {
	return &PrometheusAPIClient_Flags_Call{Call: _e.mock.On("Flags", ctx)}
}

func (_c *PrometheusAPIClient_Flags_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_Flags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Flags_Call) Return(flagsResult v1.FlagsResult, err error) *PrometheusAPIClient_Flags_Call {
	_c.Call.Return(flagsResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Flags_Call) RunAndReturn(run func(ctx context.Context) (v1.FlagsResult, error)) *PrometheusAPIClient_Flags_Call {
	_c.Call.Return(run)
	return _c
}

// LabelNames provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) LabelNames(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option) ([]string, v1.Warnings, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, matches, startTime, endTime, opts)
	} else {
		tmpRet = _mock.Called(ctx, matches, startTime, endTime)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LabelNames")
	}

	var r0 []string
	var r1 v1.Warnings
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) ([]string, v1.Warnings, error)); ok {
		return returnFunc(ctx, matches, startTime, endTime, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) []string); ok {
		r0 = returnFunc(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) v1.Warnings); ok {
		r1 = returnFunc(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(v1.Warnings)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) error); ok {
		r2 = returnFunc(ctx, matches, startTime, endTime, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PrometheusAPIClient_LabelNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LabelNames'
type PrometheusAPIClient_LabelNames_Call struct {
	*mock.Call
}

// LabelNames is a helper method to define mock.On call
//   - ctx context.Context
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
//   - opts ...v1.Option
func (_e *PrometheusAPIClient_Expecter) LabelNames(ctx interface{}, matches interface{}, startTime interface{}, endTime interface{}, opts ...interface{}) *PrometheusAPIClient_LabelNames_Call {
	return &PrometheusAPIClient_LabelNames_Call{Call: _e.mock.On("LabelNames",
		append([]interface{}{ctx, matches, startTime, endTime}, opts...)...)}
}

func (_c *PrometheusAPIClient_LabelNames_Call) Run(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option)) *PrometheusAPIClient_LabelNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 []v1.Option
		var variadicArgs []v1.Option
		if len(args) > 4 {
			variadicArgs = args[4].([]v1.Option)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_LabelNames_Call) Return(strings []string, warnings v1.Warnings, err error) *PrometheusAPIClient_LabelNames_Call {
	_c.Call.Return(strings, warnings, err)
	return _c
}

func (_c *PrometheusAPIClient_LabelNames_Call) RunAndReturn(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option) ([]string, v1.Warnings, error)) *PrometheusAPIClient_LabelNames_Call {
	_c.Call.Return(run)
	return _c
}

// LabelValues provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) LabelValues(ctx context.Context, label string, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option) (model.LabelValues, v1.Warnings, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, label, matches, startTime, endTime, opts)
	} else {
		tmpRet = _mock.Called(ctx, label, matches, startTime, endTime)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LabelValues")
	}

	var r0 model.LabelValues
	var r1 v1.Warnings
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, time.Time, time.Time, ...v1.Option) (model.LabelValues, v1.Warnings, error)); ok {
		return returnFunc(ctx, label, matches, startTime, endTime, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, time.Time, time.Time, ...v1.Option) model.LabelValues); ok {
		r0 = returnFunc(ctx, label, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.LabelValues)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, time.Time, time.Time, ...v1.Option) v1.Warnings); ok {
		r1 = returnFunc(ctx, label, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(v1.Warnings)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []string, time.Time, time.Time, ...v1.Option) error); ok {
		r2 = returnFunc(ctx, label, matches, startTime, endTime, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PrometheusAPIClient_LabelValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LabelValues'
type PrometheusAPIClient_LabelValues_Call struct {
	*mock.Call
}

// LabelValues is a helper method to define mock.On call
//   - ctx context.Context
//   - label string
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
//   - opts ...v1.Option
func (_e *PrometheusAPIClient_Expecter) LabelValues(ctx interface{}, label interface{}, matches interface{}, startTime interface{}, endTime interface{}, opts ...interface{}) *PrometheusAPIClient_LabelValues_Call {
	return &PrometheusAPIClient_LabelValues_Call{Call: _e.mock.On("LabelValues",
		append([]interface{}{ctx, label, matches, startTime, endTime}, opts...)...)}
}

func (_c *PrometheusAPIClient_LabelValues_Call) Run(run func(ctx context.Context, label string, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option)) *PrometheusAPIClient_LabelValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 []v1.Option
		var variadicArgs []v1.Option
		if len(args) > 5 {
			variadicArgs = args[5].([]v1.Option)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_LabelValues_Call) Return(labelValues model.LabelValues, warnings v1.Warnings, err error) *PrometheusAPIClient_LabelValues_Call {
	_c.Call.Return(labelValues, warnings, err)
	return _c
}

func (_c *PrometheusAPIClient_LabelValues_Call) RunAndReturn(run func(ctx context.Context, label string, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option) (model.LabelValues, v1.Warnings, error)) *PrometheusAPIClient_LabelValues_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Metadata(ctx context.Context, metric string, limit string) (map[string][]v1.Metadata, error) {
	ret := _mock.Called(ctx, metric, limit)

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 map[string][]v1.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (map[string][]v1.Metadata, error)); ok {
		return returnFunc(ctx, metric, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) map[string][]v1.Metadata); ok {
		r0 = returnFunc(ctx, metric, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]v1.Metadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, metric, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type PrometheusAPIClient_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
//   - ctx context.Context
//   - metric string
//   - limit string
func (_e *PrometheusAPIClient_Expecter) Metadata(ctx interface{}, metric interface{}, limit interface{}) *PrometheusAPIClient_Metadata_Call {
	return &PrometheusAPIClient_Metadata_Call{Call: _e.mock.On("Metadata", ctx, metric, limit)}
}

func (_c *PrometheusAPIClient_Metadata_Call) Run(run func(ctx context.Context, metric string, limit string)) *PrometheusAPIClient_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Metadata_Call) Return(stringToMetadatas map[string][]v1.Metadata, err error) *PrometheusAPIClient_Metadata_Call {
	_c.Call.Return(stringToMetadatas, err)
	return _c
}

func (_c *PrometheusAPIClient_Metadata_Call) RunAndReturn(run func(ctx context.Context, metric string, limit string) (map[string][]v1.Metadata, error)) *PrometheusAPIClient_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Query(ctx context.Context, query string, ts time.Time, opts ...v1.Option) (model.Value, v1.Warnings, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, query, ts, opts)
	} else {
		tmpRet = _mock.Called(ctx, query, ts)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 model.Value
	var r1 v1.Warnings
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, ...v1.Option) (model.Value, v1.Warnings, error)); ok {
		return returnFunc(ctx, query, ts, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, ...v1.Option) model.Value); ok {
		r0 = returnFunc(ctx, query, ts, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Value)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, ...v1.Option) v1.Warnings); ok {
		r1 = returnFunc(ctx, query, ts, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(v1.Warnings)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, time.Time, ...v1.Option) error); ok {
		r2 = returnFunc(ctx, query, ts, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PrometheusAPIClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type PrometheusAPIClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - ts time.Time
//   - opts ...v1.Option
func (_e *PrometheusAPIClient_Expecter) Query(ctx interface{}, query interface{}, ts interface{}, opts ...interface{}) *PrometheusAPIClient_Query_Call {
	return &PrometheusAPIClient_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, query, ts}, opts...)...)}
}

func (_c *PrometheusAPIClient_Query_Call) Run(run func(ctx context.Context, query string, ts time.Time, opts ...v1.Option)) *PrometheusAPIClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 []v1.Option
		var variadicArgs []v1.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]v1.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Query_Call) Return(value model.Value, warnings v1.Warnings, err error) *PrometheusAPIClient_Query_Call {
	_c.Call.Return(value, warnings, err)
	return _c
}

func (_c *PrometheusAPIClient_Query_Call) RunAndReturn(run func(ctx context.Context, query string, ts time.Time, opts ...v1.Option) (model.Value, v1.Warnings, error)) *PrometheusAPIClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryExemplars provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) QueryExemplars(ctx context.Context, query string, startTime time.Time, endTime time.Time) ([]v1.ExemplarQueryResult, error) {
	ret := _mock.Called(ctx, query, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for QueryExemplars")
	}

	var r0 []v1.ExemplarQueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]v1.ExemplarQueryResult, error)); ok {
		return returnFunc(ctx, query, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []v1.ExemplarQueryResult); ok {
		r0 = returnFunc(ctx, query, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.ExemplarQueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, query, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_QueryExemplars_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryExemplars'
type PrometheusAPIClient_QueryExemplars_Call struct {
	*mock.Call
}

// QueryExemplars is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - startTime time.Time
//   - endTime time.Time
func (_e *PrometheusAPIClient_Expecter) QueryExemplars(ctx interface{}, query interface{}, startTime interface{}, endTime interface{}) *PrometheusAPIClient_QueryExemplars_Call {
	return &PrometheusAPIClient_QueryExemplars_Call{Call: _e.mock.On("QueryExemplars", ctx, query, startTime, endTime)}
}

func (_c *PrometheusAPIClient_QueryExemplars_Call) Run(run func(ctx context.Context, query string, startTime time.Time, endTime time.Time)) *PrometheusAPIClient_QueryExemplars_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_QueryExemplars_Call) Return(exemplarQueryResults []v1.ExemplarQueryResult, err error) *PrometheusAPIClient_QueryExemplars_Call {
	_c.Call.Return(exemplarQueryResults, err)
	return _c
}

func (_c *PrometheusAPIClient_QueryExemplars_Call) RunAndReturn(run func(ctx context.Context, query string, startTime time.Time, endTime time.Time) ([]v1.ExemplarQueryResult, error)) *PrometheusAPIClient_QueryExemplars_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRange provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) QueryRange(ctx context.Context, query string, r v1.Range, opts ...v1.Option) (model.Value, v1.Warnings, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, query, r, opts)
	} else {
		tmpRet = _mock.Called(ctx, query, r)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRange")
	}

	var r0 model.Value
	var r1 v1.Warnings
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v1.Range, ...v1.Option) (model.Value, v1.Warnings, error)); ok {
		return returnFunc(ctx, query, r, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v1.Range, ...v1.Option) model.Value); ok {
		r0 = returnFunc(ctx, query, r, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Value)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v1.Range, ...v1.Option) v1.Warnings); ok {
		r1 = returnFunc(ctx, query, r, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(v1.Warnings)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, v1.Range, ...v1.Option) error); ok {
		r2 = returnFunc(ctx, query, r, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PrometheusAPIClient_QueryRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRange'
type PrometheusAPIClient_QueryRange_Call struct {
	*mock.Call
}

// QueryRange is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - r v1.Range
//   - opts ...v1.Option
func (_e *PrometheusAPIClient_Expecter) QueryRange(ctx interface{}, query interface{}, r interface{}, opts ...interface{}) *PrometheusAPIClient_QueryRange_Call {
	return &PrometheusAPIClient_QueryRange_Call{Call: _e.mock.On("QueryRange",
		append([]interface{}{ctx, query, r}, opts...)...)}
}

func (_c *PrometheusAPIClient_QueryRange_Call) Run(run func(ctx context.Context, query string, r v1.Range, opts ...v1.Option)) *PrometheusAPIClient_QueryRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v1.Range
		if args[2] != nil {
			arg2 = args[2].(v1.Range)
		}
		var arg3 []v1.Option
		var variadicArgs []v1.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]v1.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_QueryRange_Call) Return(value model.Value, warnings v1.Warnings, err error) *PrometheusAPIClient_QueryRange_Call {
	_c.Call.Return(value, warnings, err)
	return _c
}

func (_c *PrometheusAPIClient_QueryRange_Call) RunAndReturn(run func(ctx context.Context, query string, r v1.Range, opts ...v1.Option) (model.Value, v1.Warnings, error)) *PrometheusAPIClient_QueryRange_Call {
	_c.Call.Return(run)
	return _c
}

// Rules provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Rules(ctx context.Context) (v1.RulesResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rules")
	}

	var r0 v1.RulesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.RulesResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.RulesResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.RulesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Rules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rules'
type PrometheusAPIClient_Rules_Call struct {
	*mock.Call
}

// Rules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) Rules(ctx interface{}) *PrometheusAPIClient_Rules_Call {
	return &PrometheusAPIClient_Rules_Call{Call: _e.mock.On("Rules", ctx)}
}

func (_c *PrometheusAPIClient_Rules_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_Rules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Rules_Call) Return(rulesResult v1.RulesResult, err error) *PrometheusAPIClient_Rules_Call {
	_c.Call.Return(rulesResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Rules_Call) RunAndReturn(run func(ctx context.Context) (v1.RulesResult, error)) *PrometheusAPIClient_Rules_Call {
	_c.Call.Return(run)
	return _c
}

// Runtimeinfo provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Runtimeinfo(ctx context.Context) (v1.RuntimeinfoResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Runtimeinfo")
	}

	var r0 v1.RuntimeinfoResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.RuntimeinfoResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.RuntimeinfoResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.RuntimeinfoResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Runtimeinfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Runtimeinfo'
type PrometheusAPIClient_Runtimeinfo_Call struct {
	*mock.Call
}

// Runtimeinfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) Runtimeinfo(ctx interface{}) *PrometheusAPIClient_Runtimeinfo_Call {
	return &PrometheusAPIClient_Runtimeinfo_Call{Call: _e.mock.On("Runtimeinfo", ctx)}
}

func (_c *PrometheusAPIClient_Runtimeinfo_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_Runtimeinfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Runtimeinfo_Call) Return(runtimeinfoResult v1.RuntimeinfoResult, err error) *PrometheusAPIClient_Runtimeinfo_Call {
	_c.Call.Return(runtimeinfoResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Runtimeinfo_Call) RunAndReturn(run func(ctx context.Context) (v1.RuntimeinfoResult, error)) *PrometheusAPIClient_Runtimeinfo_Call {
	_c.Call.Return(run)
	return _c
}

// Series provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Series(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option) ([]model.LabelSet, v1.Warnings, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, matches, startTime, endTime, opts)
	} else {
		tmpRet = _mock.Called(ctx, matches, startTime, endTime)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Series")
	}

	var r0 []model.LabelSet
	var r1 v1.Warnings
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) ([]model.LabelSet, v1.Warnings, error)); ok {
		return returnFunc(ctx, matches, startTime, endTime, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) []model.LabelSet); ok {
		r0 = returnFunc(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LabelSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) v1.Warnings); ok {
		r1 = returnFunc(ctx, matches, startTime, endTime, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(v1.Warnings)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string, time.Time, time.Time, ...v1.Option) error); ok {
		r2 = returnFunc(ctx, matches, startTime, endTime, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PrometheusAPIClient_Series_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Series'
type PrometheusAPIClient_Series_Call struct {
	*mock.Call
}

// Series is a helper method to define mock.On call
//   - ctx context.Context
//   - matches []string
//   - startTime time.Time
//   - endTime time.Time
//   - opts ...v1.Option
func (_e *PrometheusAPIClient_Expecter) Series(ctx interface{}, matches interface{}, startTime interface{}, endTime interface{}, opts ...interface{}) *PrometheusAPIClient_Series_Call {
	return &PrometheusAPIClient_Series_Call{Call: _e.mock.On("Series",
		append([]interface{}{ctx, matches, startTime, endTime}, opts...)...)}
}

func (_c *PrometheusAPIClient_Series_Call) Run(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option)) *PrometheusAPIClient_Series_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 []v1.Option
		var variadicArgs []v1.Option
		if len(args) > 4 {
			variadicArgs = args[4].([]v1.Option)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Series_Call) Return(labelSets []model.LabelSet, warnings v1.Warnings, err error) *PrometheusAPIClient_Series_Call {
	_c.Call.Return(labelSets, warnings, err)
	return _c
}

func (_c *PrometheusAPIClient_Series_Call) RunAndReturn(run func(ctx context.Context, matches []string, startTime time.Time, endTime time.Time, opts ...v1.Option) ([]model.LabelSet, v1.Warnings, error)) *PrometheusAPIClient_Series_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Snapshot(ctx context.Context, skipHead bool) (v1.SnapshotResult, error) {
	ret := _mock.Called(ctx, skipHead)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 v1.SnapshotResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) (v1.SnapshotResult, error)); ok {
		return returnFunc(ctx, skipHead)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) v1.SnapshotResult); ok {
		r0 = returnFunc(ctx, skipHead)
	} else {
		r0 = ret.Get(0).(v1.SnapshotResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, skipHead)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type PrometheusAPIClient_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - skipHead bool
func (_e *PrometheusAPIClient_Expecter) Snapshot(ctx interface{}, skipHead interface{}) *PrometheusAPIClient_Snapshot_Call {
	return &PrometheusAPIClient_Snapshot_Call{Call: _e.mock.On("Snapshot", ctx, skipHead)}
}

func (_c *PrometheusAPIClient_Snapshot_Call) Run(run func(ctx context.Context, skipHead bool)) *PrometheusAPIClient_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Snapshot_Call) Return(snapshotResult v1.SnapshotResult, err error) *PrometheusAPIClient_Snapshot_Call {
	_c.Call.Return(snapshotResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Snapshot_Call) RunAndReturn(run func(ctx context.Context, skipHead bool) (v1.SnapshotResult, error)) *PrometheusAPIClient_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// TSDB provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) TSDB(ctx context.Context, opts ...v1.Option) (v1.TSDBResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TSDB")
	}

	var r0 v1.TSDBResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v1.Option) (v1.TSDBResult, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...v1.Option) v1.TSDBResult); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Get(0).(v1.TSDBResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...v1.Option) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_TSDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TSDB'
type PrometheusAPIClient_TSDB_Call struct {
	*mock.Call
}

// TSDB is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...v1.Option
func (_e *PrometheusAPIClient_Expecter) TSDB(ctx interface{}, opts ...interface{}) *PrometheusAPIClient_TSDB_Call {
	return &PrometheusAPIClient_TSDB_Call{Call: _e.mock.On("TSDB",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *PrometheusAPIClient_TSDB_Call) Run(run func(ctx context.Context, opts ...v1.Option)) *PrometheusAPIClient_TSDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []v1.Option
		var variadicArgs []v1.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]v1.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_TSDB_Call) Return(tSDBResult v1.TSDBResult, err error) *PrometheusAPIClient_TSDB_Call {
	_c.Call.Return(tSDBResult, err)
	return _c
}

func (_c *PrometheusAPIClient_TSDB_Call) RunAndReturn(run func(ctx context.Context, opts ...v1.Option) (v1.TSDBResult, error)) *PrometheusAPIClient_TSDB_Call {
	_c.Call.Return(run)
	return _c
}

// Targets provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) Targets(ctx context.Context) (v1.TargetsResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Targets")
	}

	var r0 v1.TargetsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.TargetsResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.TargetsResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.TargetsResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_Targets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Targets'
type PrometheusAPIClient_Targets_Call struct {
	*mock.Call
}

// Targets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) Targets(ctx interface{}) *PrometheusAPIClient_Targets_Call {
	return &PrometheusAPIClient_Targets_Call{Call: _e.mock.On("Targets", ctx)}
}

func (_c *PrometheusAPIClient_Targets_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_Targets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_Targets_Call) Return(targetsResult v1.TargetsResult, err error) *PrometheusAPIClient_Targets_Call {
	_c.Call.Return(targetsResult, err)
	return _c
}

func (_c *PrometheusAPIClient_Targets_Call) RunAndReturn(run func(ctx context.Context) (v1.TargetsResult, error)) *PrometheusAPIClient_Targets_Call {
	_c.Call.Return(run)
	return _c
}

// TargetsMetadata provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) TargetsMetadata(ctx context.Context, matchTarget string, metric string, limit string) ([]v1.MetricMetadata, error) {
	ret := _mock.Called(ctx, matchTarget, metric, limit)

	if len(ret) == 0 {
		panic("no return value specified for TargetsMetadata")
	}

	var r0 []v1.MetricMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]v1.MetricMetadata, error)); ok {
		return returnFunc(ctx, matchTarget, metric, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []v1.MetricMetadata); ok {
		r0 = returnFunc(ctx, matchTarget, metric, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.MetricMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, matchTarget, metric, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_TargetsMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetsMetadata'
type PrometheusAPIClient_TargetsMetadata_Call struct {
	*mock.Call
}

// TargetsMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - matchTarget string
//   - metric string
//   - limit string
func (_e *PrometheusAPIClient_Expecter) TargetsMetadata(ctx interface{}, matchTarget interface{}, metric interface{}, limit interface{}) *PrometheusAPIClient_TargetsMetadata_Call {
	return &PrometheusAPIClient_TargetsMetadata_Call{Call: _e.mock.On("TargetsMetadata", ctx, matchTarget, metric, limit)}
}

func (_c *PrometheusAPIClient_TargetsMetadata_Call) Run(run func(ctx context.Context, matchTarget string, metric string, limit string)) *PrometheusAPIClient_TargetsMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_TargetsMetadata_Call) Return(metricMetadatas []v1.MetricMetadata, err error) *PrometheusAPIClient_TargetsMetadata_Call {
	_c.Call.Return(metricMetadatas, err)
	return _c
}

func (_c *PrometheusAPIClient_TargetsMetadata_Call) RunAndReturn(run func(ctx context.Context, matchTarget string, metric string, limit string) ([]v1.MetricMetadata, error)) *PrometheusAPIClient_TargetsMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// WalReplay provides a mock function for the type PrometheusAPIClient
func (_mock *PrometheusAPIClient) WalReplay(ctx context.Context) (v1.WalReplayStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WalReplay")
	}

	var r0 v1.WalReplayStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (v1.WalReplayStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) v1.WalReplayStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(v1.WalReplayStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PrometheusAPIClient_WalReplay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalReplay'
type PrometheusAPIClient_WalReplay_Call struct {
	*mock.Call
}

// WalReplay is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PrometheusAPIClient_Expecter) WalReplay(ctx interface{}) *PrometheusAPIClient_WalReplay_Call {
	return &PrometheusAPIClient_WalReplay_Call{Call: _e.mock.On("WalReplay", ctx)}
}

func (_c *PrometheusAPIClient_WalReplay_Call) Run(run func(ctx context.Context)) *PrometheusAPIClient_WalReplay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PrometheusAPIClient_WalReplay_Call) Return(walReplayStatus v1.WalReplayStatus, err error) *PrometheusAPIClient_WalReplay_Call {
	_c.Call.Return(walReplayStatus, err)
	return _c
}

func (_c *PrometheusAPIClient_WalReplay_Call) RunAndReturn(run func(ctx context.Context) (v1.WalReplayStatus, error)) *PrometheusAPIClient_WalReplay_Call {
	_c.Call.Return(run)
	return _c
}
