// Code generated by mockery v2.53.3. DO NOT EDIT.

package generatemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	slo "github.com/slok/sloth/internal/pluginengine/slo"
)

// SLOPluginGetter is an autogenerated mock type for the SLOPluginGetter type
type SLOPluginGetter struct {
	mock.Mock
}

// GetSLOPlugin provides a mock function with given fields: ctx, id
func (_m *SLOPluginGetter) GetSLOPlugin(ctx context.Context, id string) (*slo.Plugin, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSLOPlugin")
	}

	var r0 *slo.Plugin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*slo.Plugin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *slo.Plugin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slo.Plugin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSLOPluginGetter creates a new instance of SLOPluginGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLOPluginGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLOPluginGetter {
	mock := &SLOPluginGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
