// Code generated by mockery v2.5.1. DO NOT EDIT.

package k8sprometheusmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
)

// PrometheusRulesEnsurer is an autogenerated mock type for the PrometheusRulesEnsurer type
type PrometheusRulesEnsurer struct {
	mock.Mock
}

// EnsurePrometheusRule provides a mock function with given fields: ctx, pr
func (_m *PrometheusRulesEnsurer) EnsurePrometheusRule(ctx context.Context, pr *v1.PrometheusRule) error {
	ret := _m.Called(ctx, pr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PrometheusRule) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
