// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package uimock

import (
	"context"

	"github.com/slok/sloth/internal/http/backend/app"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceApp creates a new instance of ServiceApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceApp {
	mock := &ServiceApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceApp is an autogenerated mock type for the ServiceApp type
type ServiceApp struct {
	mock.Mock
}

type ServiceApp_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceApp) EXPECT() *ServiceApp_Expecter {
	return &ServiceApp_Expecter{mock: &_m.Mock}
}

// GetSLO provides a mock function for the type ServiceApp
func (_mock *ServiceApp) GetSLO(ctx context.Context, req app.GetSLORequest) (*app.GetSLOResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSLO")
	}

	var r0 *app.GetSLOResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetSLORequest) (*app.GetSLOResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetSLORequest) *app.GetSLOResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.GetSLOResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.GetSLORequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceApp_GetSLO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSLO'
type ServiceApp_GetSLO_Call struct {
	*mock.Call
}

// GetSLO is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.GetSLORequest
func (_e *ServiceApp_Expecter) GetSLO(ctx interface{}, req interface{}) *ServiceApp_GetSLO_Call {
	return &ServiceApp_GetSLO_Call{Call: _e.mock.On("GetSLO", ctx, req)}
}

func (_c *ServiceApp_GetSLO_Call) Run(run func(ctx context.Context, req app.GetSLORequest)) *ServiceApp_GetSLO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.GetSLORequest
		if args[1] != nil {
			arg1 = args[1].(app.GetSLORequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceApp_GetSLO_Call) Return(getSLOResponse *app.GetSLOResponse, err error) *ServiceApp_GetSLO_Call {
	_c.Call.Return(getSLOResponse, err)
	return _c
}

func (_c *ServiceApp_GetSLO_Call) RunAndReturn(run func(ctx context.Context, req app.GetSLORequest) (*app.GetSLOResponse, error)) *ServiceApp_GetSLO_Call {
	_c.Call.Return(run)
	return _c
}

// ListBurnedBudgetRange provides a mock function for the type ServiceApp
func (_mock *ServiceApp) ListBurnedBudgetRange(ctx context.Context, req app.ListBurnedBudgetRangeRequest) (*app.ListBurnedBudgetRangeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListBurnedBudgetRange")
	}

	var r0 *app.ListBurnedBudgetRangeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListBurnedBudgetRangeRequest) (*app.ListBurnedBudgetRangeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListBurnedBudgetRangeRequest) *app.ListBurnedBudgetRangeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListBurnedBudgetRangeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListBurnedBudgetRangeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceApp_ListBurnedBudgetRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBurnedBudgetRange'
type ServiceApp_ListBurnedBudgetRange_Call struct {
	*mock.Call
}

// ListBurnedBudgetRange is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListBurnedBudgetRangeRequest
func (_e *ServiceApp_Expecter) ListBurnedBudgetRange(ctx interface{}, req interface{}) *ServiceApp_ListBurnedBudgetRange_Call {
	return &ServiceApp_ListBurnedBudgetRange_Call{Call: _e.mock.On("ListBurnedBudgetRange", ctx, req)}
}

func (_c *ServiceApp_ListBurnedBudgetRange_Call) Run(run func(ctx context.Context, req app.ListBurnedBudgetRangeRequest)) *ServiceApp_ListBurnedBudgetRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListBurnedBudgetRangeRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListBurnedBudgetRangeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceApp_ListBurnedBudgetRange_Call) Return(listBurnedBudgetRangeResponse *app.ListBurnedBudgetRangeResponse, err error) *ServiceApp_ListBurnedBudgetRange_Call {
	_c.Call.Return(listBurnedBudgetRangeResponse, err)
	return _c
}

func (_c *ServiceApp_ListBurnedBudgetRange_Call) RunAndReturn(run func(ctx context.Context, req app.ListBurnedBudgetRangeRequest) (*app.ListBurnedBudgetRangeResponse, error)) *ServiceApp_ListBurnedBudgetRange_Call {
	_c.Call.Return(run)
	return _c
}

// ListSLIAvailabilityRange provides a mock function for the type ServiceApp
func (_mock *ServiceApp) ListSLIAvailabilityRange(ctx context.Context, req app.ListSLIAvailabilityRangeRequest) (*app.ListSLIAvailabilityRangeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSLIAvailabilityRange")
	}

	var r0 *app.ListSLIAvailabilityRangeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLIAvailabilityRangeRequest) (*app.ListSLIAvailabilityRangeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLIAvailabilityRangeRequest) *app.ListSLIAvailabilityRangeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListSLIAvailabilityRangeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListSLIAvailabilityRangeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceApp_ListSLIAvailabilityRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLIAvailabilityRange'
type ServiceApp_ListSLIAvailabilityRange_Call struct {
	*mock.Call
}

// ListSLIAvailabilityRange is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListSLIAvailabilityRangeRequest
func (_e *ServiceApp_Expecter) ListSLIAvailabilityRange(ctx interface{}, req interface{}) *ServiceApp_ListSLIAvailabilityRange_Call {
	return &ServiceApp_ListSLIAvailabilityRange_Call{Call: _e.mock.On("ListSLIAvailabilityRange", ctx, req)}
}

func (_c *ServiceApp_ListSLIAvailabilityRange_Call) Run(run func(ctx context.Context, req app.ListSLIAvailabilityRangeRequest)) *ServiceApp_ListSLIAvailabilityRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListSLIAvailabilityRangeRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListSLIAvailabilityRangeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceApp_ListSLIAvailabilityRange_Call) Return(listSLIAvailabilityRangeResponse *app.ListSLIAvailabilityRangeResponse, err error) *ServiceApp_ListSLIAvailabilityRange_Call {
	_c.Call.Return(listSLIAvailabilityRangeResponse, err)
	return _c
}

func (_c *ServiceApp_ListSLIAvailabilityRange_Call) RunAndReturn(run func(ctx context.Context, req app.ListSLIAvailabilityRangeRequest) (*app.ListSLIAvailabilityRangeResponse, error)) *ServiceApp_ListSLIAvailabilityRange_Call {
	_c.Call.Return(run)
	return _c
}

// ListSLOs provides a mock function for the type ServiceApp
func (_mock *ServiceApp) ListSLOs(ctx context.Context, req app.ListSLOsRequest) (*app.ListSLOsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSLOs")
	}

	var r0 *app.ListSLOsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLOsRequest) (*app.ListSLOsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLOsRequest) *app.ListSLOsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListSLOsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListSLOsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceApp_ListSLOs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLOs'
type ServiceApp_ListSLOs_Call struct {
	*mock.Call
}

// ListSLOs is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListSLOsRequest
func (_e *ServiceApp_Expecter) ListSLOs(ctx interface{}, req interface{}) *ServiceApp_ListSLOs_Call {
	return &ServiceApp_ListSLOs_Call{Call: _e.mock.On("ListSLOs", ctx, req)}
}

func (_c *ServiceApp_ListSLOs_Call) Run(run func(ctx context.Context, req app.ListSLOsRequest)) *ServiceApp_ListSLOs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListSLOsRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListSLOsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceApp_ListSLOs_Call) Return(listSLOsResponse *app.ListSLOsResponse, err error) *ServiceApp_ListSLOs_Call {
	_c.Call.Return(listSLOsResponse, err)
	return _c
}

func (_c *ServiceApp_ListSLOs_Call) RunAndReturn(run func(ctx context.Context, req app.ListSLOsRequest) (*app.ListSLOsResponse, error)) *ServiceApp_ListSLOs_Call {
	_c.Call.Return(run)
	return _c
}

// ListServices provides a mock function for the type ServiceApp
func (_mock *ServiceApp) ListServices(ctx context.Context, req app.ListServicesRequest) (*app.ListServicesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 *app.ListServicesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListServicesRequest) (*app.ListServicesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListServicesRequest) *app.ListServicesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListServicesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListServicesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceApp_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type ServiceApp_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListServicesRequest
func (_e *ServiceApp_Expecter) ListServices(ctx interface{}, req interface{}) *ServiceApp_ListServices_Call {
	return &ServiceApp_ListServices_Call{Call: _e.mock.On("ListServices", ctx, req)}
}

func (_c *ServiceApp_ListServices_Call) Run(run func(ctx context.Context, req app.ListServicesRequest)) *ServiceApp_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListServicesRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListServicesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceApp_ListServices_Call) Return(listServicesResponse *app.ListServicesResponse, err error) *ServiceApp_ListServices_Call {
	_c.Call.Return(listServicesResponse, err)
	return _c
}

func (_c *ServiceApp_ListServices_Call) RunAndReturn(run func(ctx context.Context, req app.ListServicesRequest) (*app.ListServicesResponse, error)) *ServiceApp_ListServices_Call {
	_c.Call.Return(run)
	return _c
}
