// Code generated by 'yaegi extract github.com/slok/sloth/pkg/common/utils/k8s'. DO NOT EDIT.

package custom

import (
	"github.com/slok/sloth/pkg/common/utils/k8s"
	"reflect"
)

func init() {
	Symbols["github.com/slok/sloth/pkg/common/utils/k8s/k8s"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"PromRuleGroupToUnstructuredPromOperator": reflect.ValueOf(k8s.PromRuleGroupToUnstructuredPromOperator),
		"UnstructuredToYAMLString":                reflect.ValueOf(k8s.UnstructuredToYAMLString),
	}
}
