// Code generated by 'yaegi extract github.com/slok/sloth/pkg/common/utils/prometheus'. DO NOT EDIT.

package custom

import (
	"github.com/slok/sloth/pkg/common/utils/prometheus"
	"reflect"
)

func init() {
	Symbols["github.com/slok/sloth/pkg/common/utils/prometheus/prometheus"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LabelsToPromFilter":    reflect.ValueOf(prometheus.LabelsToPromFilter),
		"PromStrToTimeDuration": reflect.ValueOf(prometheus.PromStrToTimeDuration),
		"TimeDurationToPromStr": reflect.ValueOf(prometheus.TimeDurationToPromStr),
	}
}
