// Code generated by 'yaegi extract github.com/slok/sloth/pkg/common/utils/data'. DO NOT EDIT.

package custom

import (
	"github.com/slok/sloth/pkg/common/utils/data"
	"reflect"
)

func init() {
	Symbols["github.com/slok/sloth/pkg/common/utils/data/data"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"MergeLabels": reflect.ValueOf(data.MergeLabels),
		"SplitYAML":   reflect.ValueOf(data.SplitYAML),
	}
}
