// Code generated by 'yaegi extract k8s.io/apimachinery/pkg/apis/meta/v1/unstructured'. DO NOT EDIT.

package custom

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"reflect"
)

func init() {
	Symbols["k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NestedBool":                  reflect.ValueOf(unstructured.NestedBool),
		"NestedFieldCopy":             reflect.ValueOf(unstructured.NestedFieldCopy),
		"NestedFieldNoCopy":           reflect.ValueOf(unstructured.NestedFieldNoCopy),
		"NestedFloat64":               reflect.ValueOf(unstructured.NestedFloat64),
		"NestedInt64":                 reflect.ValueOf(unstructured.NestedInt64),
		"NestedMap":                   reflect.ValueOf(unstructured.NestedMap),
		"NestedNullCoercingStringMap": reflect.ValueOf(unstructured.NestedNullCoercingStringMap),
		"NestedNumberAsFloat64":       reflect.ValueOf(unstructured.NestedNumberAsFloat64),
		"NestedSlice":                 reflect.ValueOf(unstructured.NestedSlice),
		"NestedString":                reflect.ValueOf(unstructured.NestedString),
		"NestedStringMap":             reflect.ValueOf(unstructured.NestedStringMap),
		"NestedStringSlice":           reflect.ValueOf(unstructured.NestedStringSlice),
		"NewJSONFallbackEncoder":      reflect.ValueOf(unstructured.NewJSONFallbackEncoder),
		"RemoveNestedField":           reflect.ValueOf(unstructured.RemoveNestedField),
		"SetNestedField":              reflect.ValueOf(unstructured.SetNestedField),
		"SetNestedMap":                reflect.ValueOf(unstructured.SetNestedMap),
		"SetNestedSlice":              reflect.ValueOf(unstructured.SetNestedSlice),
		"SetNestedStringMap":          reflect.ValueOf(unstructured.SetNestedStringMap),
		"SetNestedStringSlice":        reflect.ValueOf(unstructured.SetNestedStringSlice),
		"UnstructuredJSONScheme":      reflect.ValueOf(&unstructured.UnstructuredJSONScheme).Elem(),

		// type definitions
		"Unstructured":     reflect.ValueOf((*unstructured.Unstructured)(nil)),
		"UnstructuredList": reflect.ValueOf((*unstructured.UnstructuredList)(nil)),
	}
}
