// Code generated by 'yaegi extract github.com/VictoriaMetrics/metricsql'. DO NOT EDIT.

package custom

import (
	"github.com/VictoriaMetrics/metricsql"
	"reflect"
)

func init() {
	Symbols["github.com/VictoriaMetrics/metricsql/metricsql"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Clone":                      reflect.ValueOf(metricsql.Clone),
		"CompileRegexp":              reflect.ValueOf(metricsql.CompileRegexp),
		"CompileRegexpAnchored":      reflect.ValueOf(metricsql.CompileRegexpAnchored),
		"DurationValue":              reflect.ValueOf(metricsql.DurationValue),
		"ExpandWithExprs":            reflect.ValueOf(metricsql.ExpandWithExprs),
		"GetRollupArgIdx":            reflect.ValueOf(metricsql.GetRollupArgIdx),
		"IsAggrFunc":                 reflect.ValueOf(metricsql.IsAggrFunc),
		"IsBinaryOpCmp":              reflect.ValueOf(metricsql.IsBinaryOpCmp),
		"IsLikelyInvalid":            reflect.ValueOf(metricsql.IsLikelyInvalid),
		"IsRollupFunc":               reflect.ValueOf(metricsql.IsRollupFunc),
		"IsSupportedFunction":        reflect.ValueOf(metricsql.IsSupportedFunction),
		"IsTransformFunc":            reflect.ValueOf(metricsql.IsTransformFunc),
		"Optimize":                   reflect.ValueOf(metricsql.Optimize),
		"Parse":                      reflect.ValueOf(metricsql.Parse),
		"PositiveDurationValue":      reflect.ValueOf(metricsql.PositiveDurationValue),
		"Prettify":                   reflect.ValueOf(metricsql.Prettify),
		"PushdownBinaryOpFilters":    reflect.ValueOf(metricsql.PushdownBinaryOpFilters),
		"TrimFiltersByGroupModifier": reflect.ValueOf(metricsql.TrimFiltersByGroupModifier),
		"VisitAll":                   reflect.ValueOf(metricsql.VisitAll),

		// type definitions
		"AggrFuncExpr": reflect.ValueOf((*metricsql.AggrFuncExpr)(nil)),
		"BinaryOpExpr": reflect.ValueOf((*metricsql.BinaryOpExpr)(nil)),
		"DurationExpr": reflect.ValueOf((*metricsql.DurationExpr)(nil)),
		"Expr":         reflect.ValueOf((*metricsql.Expr)(nil)),
		"FuncExpr":     reflect.ValueOf((*metricsql.FuncExpr)(nil)),
		"LabelFilter":  reflect.ValueOf((*metricsql.LabelFilter)(nil)),
		"MetricExpr":   reflect.ValueOf((*metricsql.MetricExpr)(nil)),
		"ModifierExpr": reflect.ValueOf((*metricsql.ModifierExpr)(nil)),
		"NumberExpr":   reflect.ValueOf((*metricsql.NumberExpr)(nil)),
		"RollupExpr":   reflect.ValueOf((*metricsql.RollupExpr)(nil)),
		"StringExpr":   reflect.ValueOf((*metricsql.StringExpr)(nil)),

		// interface wrapper definitions
		"_Expr": reflect.ValueOf((*_github_com_VictoriaMetrics_metricsql_Expr)(nil)),
	}
}

// _github_com_VictoriaMetrics_metricsql_Expr is an interface wrapper for Expr type
type _github_com_VictoriaMetrics_metricsql_Expr struct {
	IValue        interface{}
	WAppendString func(dst []byte) []byte
}

func (W _github_com_VictoriaMetrics_metricsql_Expr) AppendString(dst []byte) []byte {
	return W.WAppendString(dst)
}
