---
# Source: sloth/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sloth
  namespace: monitoring
  labels:
    helm.sh/chart: sloth-0.7.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: sloth
---
# Source: sloth/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sloth
  labels:
    helm.sh/chart: sloth-0.7.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: sloth
rules:
  - apiGroups: ["sloth.slok.dev"]
    resources: ["*"]
    verbs: ["*"]

  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheusrules"]
    verbs: ["create", "list", "get", "update", "watch"]
---
# Source: sloth/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sloth
  labels:
    helm.sh/chart: sloth-0.7.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: sloth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sloth
subjects:
  - kind: ServiceAccount
    name: sloth
    namespace: monitoring
---
# Source: sloth/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sloth
  namespace: monitoring
  labels:
    helm.sh/chart: sloth-0.7.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: sloth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sloth
      app.kubernetes.io/name: sloth
      app.kubernetes.io/instance: sloth
  template:
    metadata:
      labels:
        helm.sh/chart: sloth-0.7.1
        app.kubernetes.io/managed-by: Helm
        app: sloth
        app.kubernetes.io/name: sloth
        app.kubernetes.io/instance: sloth
      annotations:
        kubectl.kubernetes.io/default-container: sloth
    spec:
      serviceAccountName: sloth
      containers:
        - name: sloth
          image: ghcr.io/slok/sloth:v0.11.0
          args:
            - kubernetes-controller
          ports:
            - containerPort: 8081
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 150Mi
            requests:
              cpu: 5m
              memory: 75Mi
---
# Source: sloth/templates/pod-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sloth
  namespace: monitoring
  labels:
    helm.sh/chart: sloth-0.7.1
    app.kubernetes.io/managed-by: Helm
    app: sloth
    app.kubernetes.io/name: sloth
    app.kubernetes.io/instance: sloth
spec:
  selector:
    matchLabels:
      app: sloth
      app.kubernetes.io/name: sloth
      app.kubernetes.io/instance: sloth
  podMetricsEndpoints:
    - port: metrics
