package k8sprometheus

import (
	"fmt"
	"github.com/slok/sloth/internal/info"
)

func MergeLabels(ms ...map[string]string) map[string]string {
	res := map[string]string{}
	for _, m := range ms {
		for k, v := range m {
			res[k] = v
		}
	}

	return res
}

func WriteTopDisclaimer(bs []byte) []byte {
	return append([]byte(disclaimer), bs...)
}

var disclaimer = fmt.Sprintf(`
---
# Code generated by Sloth (%s): https://github.com/slok/sloth.
# DO NOT EDIT.

`, info.Version)
